
src_vocab_size: 0 #128
tgt_vocab_size: 128

save_data: run/samples
src_vocab: _  # vocabs/vocab.en
tgt_vocab: vocabs/vocab.hu

# Corpus opts:
data:
    corpus:
        path_src: E://Data/hu-nmt/combined-en-hu/hunglish2-tiny-train.en
        path_tgt: E://Data/hu-nmt/combined-en-hu/hunglish2-tiny-train.hu
        weight: 1
        transforms: berttokenizer
    valid:
        path_src: E://Data/hu-nmt/combined-en-hu/hunglish2-tiny-valid.en
        path_tgt: E://Data/hu-nmt/combined-en-hu/hunglish2-tiny-valid.hu
        weight: 1
        transforms: berttokenizer

#### Subword
src_subword_model: _ #sp_models/bpe_en.model
tgt_subword_model: sp_models/bpe_hu.model
tgt_subword_nbest: 1
tgt_subword_alpha: 0.0

src_seq_length: 16  # maximum source sequence length
tgt_seq_length: 16  # maximum target sequence length

# TRAIN

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Batching
batch_size: 3
queue_size: 5
batch_type: sents
data_type: text
#accum_count: [3]

# General opts
save_model: run/model
keep_checkpoint: 10
save_checkpoint_steps: 10000
average_decay: 0.0005
seed: 1234
report_every: 2
train_steps: 40
valid_steps: 10
single_pass: False
early_stopping: 5 
early_stopping_criteria: ppl

# Optimization
model_dtype: "fp16"
optim: "adam"
learning_rate: 2.0
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 2
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
enc_layers: 2
dec_layers: 2
heads: 8
rnn_size: 768
word_vec_size: 768
enc_rnn_size: 768
src_word_vec_size: 768
tgt_word_vec_size: 768
dec_rnn_size: 768
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
#share_decoder_embeddings: true

# Logging
log_file: run/logs_no_qoutes
