
src_vocab_size: 1000 # Dummy value, must be greater than number of characters
tgt_vocab_size: 10000

save_data: run/samples
src_vocab: vocabs/vocab.en
tgt_vocab: vocabs/vocab.hu
utils_path: utils
sp_models_path: sp_models

translate_model: run/model_step_14000.pt

# pair options
pair_n_lines: 50
pair_output_path: run/pair_out.txt

data:
    corpus:
        path_src: /home1/hu-nmt/hu-nmt/data/ftp.mokk.bme.hu/Hunglish2/combined-en-hu/hunglish2-short-no-qoutes-train.en
        path_tgt: /home1/hu-nmt/hu-nmt/data/ftp.mokk.bme.hu/Hunglish2/combined-en-hu/hunglish2-short-no-qoutes-train.hu
        weight: 1
        transforms: [berttokenizer]  # Comment this during vocab generation...
    valid:
        path_src: /home1/hu-nmt/hu-nmt/data/ftp.mokk.bme.hu/Hunglish2/combined-en-hu/hunglish2-short-no-qoutes-valid.en
        path_tgt: /home1/hu-nmt/hu-nmt/data/ftp.mokk.bme.hu/Hunglish2/combined-en-hu/hunglish2-short-no-qoutes-valid.hu
        weight: 1
        transforms: [berttokenizer]  # Comment this during vocab generation...

#### Subword
src_subword_model: sp_models/bpe_en.model
tgt_subword_model: sp_models/bpe_hu.model
tgt_subword_nbest: 1
tgt_subword_alpha: 0.0

src_seq_length: 16  # maximum source sequence length
tgt_seq_length: 16  # maximum target sequence length

# TRAIN

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Batching
batch_size: 32
#queue_size: 5
batch_type: sents
data_type: text
#accum_count: [3]

# General opts
save_model: run/model
keep_checkpoint: 50 # 5 epoch
save_checkpoint_steps: 10000
average_decay: 0.0005
seed: 1234
report_every: 100
train_steps: 1500000 
valid_steps: 10000
single_pass: False
early_stopping: 20
early_stopping_criteria: ppl

# Optimization
model_dtype: "fp16"
optim: "adam"
learning_rate: 2.0
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 2
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
enc_layers: 2
dec_layers: 6
heads: 8
rnn_size: 768
word_vec_size: 768
enc_rnn_size: 768
src_word_vec_size: 768
tgt_word_vec_size: 768
dec_rnn_size: 768
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
#share_decoder_embeddings: true

# Logging
log_file: run/logs
