name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.12]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pip install poetry==${{ matrix.poetry-version }}
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install other dependencies
        run: sudo apt-get install -y graphviz graphviz-dev
      - name: Install poetry dependencies
        working-directory: ./src
        run: poetry install
      - name: Run pytest
        working-directory: ./src
        run: PYTHONPATH=. poetry run python -m pytest -v --cov=src/hu_nmt/data_augmentator src/hu_nmt/test/
      
